name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia Ã  meia-noite UTC
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    name: Build snake animation
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ GeraÃ§Ã£o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: matheusbezerrasantos2015-hash
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      - name: ğŸš€ PublicaÃ§Ã£o no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
